# Generated by Django 4.0.3 on 2022-03-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=70)),
                ('user_password', models.CharField(max_length=50)),
                ('user_gender', models.CharField(max_length=10)),
                ('user_DOB', models.DateField()),
                ('user_phoneNumber', models.IntegerField()),
                ('user_address', models.CharField(max_length=100)),
            ],
        ),
    ]
